Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 15:48:50
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

[26/Jun/2025 15:49:28] "GET /admin/users/import/ HTTP/1.1" 200 10112
[26/Jun/2025 15:49:29] "GET /static/css/style.css HTTP/1.1" 304 0
D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:14:01
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:14:52
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

[26/Jun/2025 16:22:36] "GET /admin/users/import/ HTTP/1.1" 200 11244
[26/Jun/2025 16:22:36] "GET /static/css/style.css HTTP/1.1" 304 0
[26/Jun/2025 16:22:44] "GET /admin/export/users/template/ HTTP/1.1" 200 1815
D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\easytime\Python\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\easytime\Python\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\easytime\Python\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\easytime\Python\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\easytime\Python\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Prit\GlobalProfile\gsez_profile\gsez_profile\urls.py", line 23, in <module>
    path('', include('core.urls')),
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Prit\GlobalProfile\gsez_profile\core\urls.py", line 2, in <module>
    from . import views
  File "D:\Prit\GlobalProfile\gsez_profile\core\views.py", line 1429
    json_value = json.loads(value)
    ^
IndentationError: expected an indented block after 'if' statement on line 1427
D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:27:03
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:30:02
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:31:52
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:32:36
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

[26/Jun/2025 16:34:20] "GET /admin/users/import/ HTTP/1.1" 200 10464
[26/Jun/2025 16:34:20] "GET /static/css/style.css HTTP/1.1" 304 0
[26/Jun/2025 16:34:21] "GET /admin/export/users/template/ HTTP/1.1" 200 2073
[26/Jun/2025 16:36:04] "POST /admin/users/import/ HTTP/1.1" 302 0
[26/Jun/2025 16:36:04] "GET /admin/users/ HTTP/1.1" 200 54653
D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:38:04
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:38:14
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

[26/Jun/2025 16:38:59] "GET /admin/users/ HTTP/1.1" 200 54340
[26/Jun/2025 16:38:59] "GET /static/css/style.css HTTP/1.1" 200 7726
[26/Jun/2025 16:38:59] "GET /static/js/script.js HTTP/1.1" 200 28264
Not Found: /favicon.ico
[26/Jun/2025 16:39:00] "GET /favicon.ico HTTP/1.1" 404 11307
[26/Jun/2025 16:39:47] "GET /admin/users/ HTTP/1.1" 200 54340
[26/Jun/2025 16:39:53] "GET /admin/users/edit/5/ HTTP/1.1" 200 52389
[26/Jun/2025 16:39:53] "GET /admin/users/edit/5/ HTTP/1.1" 200 52389
[26/Jun/2025 16:39:57] "GET /admin/users/detail/5/ HTTP/1.1" 200 12443
[26/Jun/2025 16:39:57] "GET /static/img/default-profile.png HTTP/1.1" 404 1828
[26/Jun/2025 16:40:09] "GET /admin/users/ HTTP/1.1" 200 54340
[26/Jun/2025 16:40:30] "GET /admin/companies/ HTTP/1.1" 200 29578
D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\easytime\Python\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\easytime\Python\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\easytime\Python\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\easytime\Python\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\easytime\Python\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Prit\GlobalProfile\gsez_profile\gsez_profile\urls.py", line 23, in <module>
    path('', include('core.urls')),
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Prit\GlobalProfile\gsez_profile\core\urls.py", line 2, in <module>
    from . import views
  File "D:\Prit\GlobalProfile\gsez_profile\core\views.py", line 1441
    if value:
IndentationError: unexpected indent
D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:53:32
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:53:46
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\easytime\Python\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\easytime\Python\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\easytime\Python\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\easytime\Python\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\easytime\Python\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Prit\GlobalProfile\gsez_profile\gsez_profile\urls.py", line 23, in <module>
    path('', include('core.urls')),
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\easytime\Python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Prit\GlobalProfile\gsez_profile\core\urls.py", line 2, in <module>
    from . import views
  File "D:\Prit\GlobalProfile\gsez_profile\core\views.py", line 1441
    if value:
IndentationError: unexpected indent
D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:54:59
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 16:55:20
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 17:39:05
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 17:39:58
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 17:40:27
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 17:40:53
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 17:41:26
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 17:41:53
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 18:11:47
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 18:16:14
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 18:17:06
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 18:17:37
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 18:18:13
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 18:18:42
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

D:\Prit\GlobalProfile\gsez_profile\core\views.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2025 - 18:19:06
Django version 4.2.2, using settings 'gsez_profile.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.

